### ISSUE TITLE
Timezone not working correctly

### ISSUE THREAD

**Issue by tezmo** [xl0e/weatherdisplay#5]
Hej,

been trying to find the problem, but can't find it so far..

Issue is: I tried both CET and CEST timezones in config: both give the wrong time (1 hour earlier) e.g. 
Current time in Central europe: 09:00

Outcome right now: 
CET 08:00
CEST 08:00 (should really be at least 1 hour more than CET!)

Can't figure out how to get the time right, without setting the wrong timezone..

**Comment by gagauz** [comment]
@tezmo What ntp timeserver do you use in config?

**Comment by geeuk** [comment]
I can confirm with uk.pool.ntp.org and GMT timezone it's working all okay.

**Comment by N1c093** [comment]
I also had the same problem and found the solution.
For reference you can find the table with the right timezones here: https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
